### ISSUE TITLE
Yaml file needs ports declaration

### ISSUE THREAD

**Issue by mprofitlich** [drud/ddev-browsersync#34]
In an unmodified installation of ddev-browsersync the script showed the ‹Browsersync: connected› badge in the browser but changes to files did not lead to a page reload.

I had to add the last two lines of the following code to make it work:
```
services:
  web:    
    ports:
      - "127.0.0.1:$DDEV_HOST_WEBSERVER_PORT:8000"
```
The solution is taken from https://stackoverflow.com/a/60994033/2041152

I use 
browser-sync 2.27.11
ddev 1.21.4
on a Macbook Air M2 with Mac OS 13.0.1

As I do not know whether these lines are valid for all use cases I, am not adding a PR.
