### ISSUE TITLE
Hot reloading

### ISSUE THREAD

**Issue by mmunz** [drud/ddev-browsersync#39]
Browser-sync can hot reload (inject) files like js and css. 

But hot reload did not work here until i changed docker-compose.browsersync.yaml from

```
#ddev-generated
# Override the web container's standard HTTP_EXPOSE and HTTPS_EXPOSE
# This is to expose the browsersync port.
services:
  web:
    expose:
      - '3000'
    environment:
      - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,3001:3000
      - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025,3000:3000
```

to
```
# Override the web container's standard HTTP_EXPOSE and HTTPS_EXPOSE
# This is to expose the browsersync port.
services:
  web:
    expose:
      - '3000'
      - '3001'
    environment:
      - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025,3000:3000,3001:3001
```

The port 3001 also needs to be routed to browsersync:3001 because browser-sync wants to establish a connection for websockets with https://demo.ddev.site:3001/browser-sync/socket.io/?EIO=4&transport=polling&t=xxx
I guess we do not need to expose any HTTP_PORTS.

**Comment by tyler36** [comment]
I'm not able to replicate the problem.


##  Test

1. Setup working Laravel demo. Confirm working.
2. Add `drud/ddev-browsersync`

    ```shell
    ddev get drud/ddev-browsersync
    ```

3. Restart DDEV to activate addon

    ```shell
    ddev restart
    ```

4. Start browsersync

    ```shell
    ddev browsersync
    ```

5. Make a change to CSS in  `public/css/app.css`. 

    ```diff
    div {
    -    color: green !important;
    +    color: red !important;
    }
    ```

You can see:

- the last inital request for `app.css` 
- websock connection on 3000 (lines 6-9)
- additional injections at the bottom.

![hotreloading](https://user-images.githubusercontent.com/7234392/213332252-a4ce0d54-cb0f-4847-b9d5-dd58a9baa2d4.png)


My `.ddev/docker-compose.browsersync.yaml`:

```yaml
#ddev-generated
# Override the web container's standard HTTP_EXPOSE and HTTPS_EXPOSE
# This is to expose the browsersync port.
services:
  web:
    expose:
      - '3000'
    environment:
      - HTTP_EXPOSE=${DDEV_ROUTER_HTTP_PORT}:80,${DDEV_MAILHOG_PORT}:8025,3001:3000
      - HTTPS_EXPOSE=${DDEV_ROUTER_HTTPS_PORT}:80,${DDEV_MAILHOG_HTTPS_PORT}:8025,3000:3000
```
